'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.gallery': 'Gallery',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact',
    'nav.booking': 'Book Now',
    // Hero Section
    'hero.eyebrow': 'Premium Barber Studio',
    'hero.welcome': 'Welcome to',
    'hero.subtext': 'Premium cuts, sharp lines, and professional grooming in Montreal.',
    'hero.cta_book': 'Book Appointment',
    'hero.cta_services': 'View Services',
    'hero.cta_call': 'Call Us',
    'hero.info_address_label': 'DreyCutz Salon',
    'hero.info_hours_label': 'Hours',
    'hero.info_hours_val': 'Mon – Sat 9am – 7pm',
    // About Section
    'about.founder_title': 'CEO & Barber',
    'about.founder_subtitle': 'Founder & CEO',
    'about.quote': 'Every cut is a craft, every detail matters.',
    'about.p1_part1': 'Not just a service provider. Every cut is a ',
    'about.p1_craft': 'craft',
    'about.p1_part2': ', every detail matters.',
    'about.p2': 'With years of experience and a passion for precision, Drey brings expertise, creativity, and dedication to every client. Book your appointment and experience the difference of a session tailored specifically to your unique structure and style.',
    'about.cta': 'Secure Your Session',
    'about.stat_experience': 'Experience',
    'about.stat_experience_val': '10+ YEARS',
    'about.stat_specialty': 'Specialty',
    'about.stat_specialty_val': 'PRECISION',
    'about.stat_location': 'Location',
    'about.stat_location_val': 'MONTRÉAL',
    // Values Section
    'values.diff_eyebrow': 'Why DreyCutz',
    'values.diff_title': 'The New Standard',
    'values.diff_desc': 'We\'ve redesigned the grooming ritual. No wait times, no compromises, just pure craft tailored to your lifestyle.',
    'values.card.time_title': 'Time-Saving',
    'values.card.time_desc': 'No wait times. Every session is reserved exclusively for you, ensuring punctuality.',
    'values.card.skill_title': 'Expert Skill',
    'values.card.skill_desc': 'Combining classic technique with modern artistry for a flawless finish.',
    'values.card.custom_title': 'Customized',
    'values.card.custom_desc': 'Your bone structure dictates the cut. We design for the individual.',
    'values.card.relax_title': 'Relaxing',
    'values.card.relax_desc': 'A calm, curated environment designed to let you recharge while we refine.',
    'values.core_eyebrow': 'Core Values',
    'values.core_title': 'What We Believe In',
    'values.val.precision_title': 'Precision',
    'values.val.precision_desc': 'Measure twice, cut once. We obsess over the micro-details so the macro-result is flawless.',
    'values.val.respect_title': 'Respect',
    'values.val.respect_desc': 'Your time is sacred. Your trust is earned. We treat every client with the utmost dignity.',
    'values.val.integrity_title': 'Integrity',
    'values.val.integrity_desc': 'Transparent pricing and honest advice. If a style doesn\'t suit you, we\'ll tell you.',
    'values.val.excellence_title': 'Excellence',
    'values.val.excellence_desc': 'Good is the enemy of great. We push the boundaries of the craft every single day.',
    'values.val.community_title': 'Community',
    'values.val.community_desc': 'A space where everyone belongs. More than a studio, we\'re a neighborhood hub.',
    'values.val.passion_title': 'Passion',
    'values.val.passion_desc': 'This isn\'t a job—it\'s an obsession. We live and breathe the art of the cut.',
    // Booking Section
    'booking.title_part1': 'Ready for a ',
    'booking.title_fresh': 'Fresh',
    'booking.title_part2': ' Cut?',
    'booking.tab_services': 'Services',
    'booking.tab_info': 'Studio Info',
    'booking.menu_title': 'Service Menu',
    'booking.menu_desc': 'Select a category to explore',
    'booking.info_call': 'Call',
    'booking.info_email': 'Email',
    'booking.info_location': 'Location',
    'booking.popular_times': 'Popular Times',
    'booking.availability_suffix': ' Availability',
    'booking.quiet': 'Quiet',
    'booking.moderate': 'Moderate',
    'booking.busy': 'Busy',
    'booking.schedule_title': 'Studio Schedule',
    // Reviews Section
    'reviews.eyebrow': 'Our Satisfied Customers',
    'reviews.title': 'The Reviews',
    'reviews.rating_label': '5.0 Rating',
    'reviews.verified_client': 'Verified Client',
    // Footer Section
    'footer.tagline': 'Premium barbershop in Montreal. Sharp cuts, clean lines, and professional grooming by Drey.',
    'footer.quick_links': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.hours': 'Hours',
    'footer.rights': 'ALL RIGHTS RESERVED.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.link.home': 'Home',
    'footer.link.services': 'Our Services',
    'footer.link.gallery': 'Gallery',
    'footer.link.why_book': 'WHY BOOK WITH US',
    'footer.link.about': 'About Us',
    'footer.link.customers': 'Satisfied Customers',
    'footer.link.faq': 'FAQ',
    'footer.link.careers': 'Careers',
    'footer.link.contact': 'Contact',
    // Info Section
    'info.eyebrow': 'Frequently Asked Questions',
    'info.title_part1': 'Essential ',
    'info.title_information': 'Information',
    'info.faq_payment_title': 'Payment Methods',
    'info.faq_payment_interac': 'Interac E-Transfer',
    'info.faq_payment_cash': 'Cash (In-Studio)',
    'info.faq_payment_note': 'A non-refundable deposit is required at the time of booking via E-Transfer.',
    'info.faq_booking_title': 'Booking Policy',
    'info.faq_booking_answer': 'All appointments must be scheduled through our online portal. Your spot is only confirmed once the CA$15 deposit is received.',
    'info.faq_late_title': 'Late Policy',
    'info.faq_late_answer': 'We value your time. If you are more than 15 minutes late, your appointment may be cancelled to stay on schedule for other clients.',
    'info.notice': 'Notice',
    'info.cancel_title': 'Cancellation Policy',
    'info.deposits_label': 'Deposits',
    'info.deposits_desc': 'Deposits are non-refundable and non-transferable if the session is cancelled.',
    'info.reschedule_label': 'Rescheduling',
    'info.reschedule_desc': 'Need to move your session? Please reach out ASAP via call or text to find a new available slot.',
    'info.protocol': 'Studio Protocol',
    // Services Section
    'services.title': 'Our Services',
    'services.explore': 'Explore Services',
    'services.category_label': 'Category',
    'services.crucial_info': 'Crucial Information',
    'services.policy_title': 'Booking Policy',
    'services.policy_desc': 'A CA$15 non-refundable deposit is required to secure your booking.',
    'services.book_button': 'Book',
    'services.next_category': 'Next',
    // Modal Section
    'modal.title_confirmed': 'Booking Confirmed!',
    'modal.title_booking': 'Book Appointment',
    'modal.ready': 'Everything is ready',
    'modal.close': 'Close',
    'modal.select_date': 'Select a Date',
    'modal.back_calendar': 'Back to Calendar',
    'modal.select_time': 'Select your preferred time',
    'modal.back_time': 'Back to Time',
    'modal.complete_details': 'Complete your details',
    'modal.first_name': 'First Name',
    'modal.last_name': 'Last Name',
    'modal.email': 'Email Address',
    'modal.phone': 'Phone Number',
    'modal.confirm_button': 'Confirm Booking',
    'modal.success_p1_part1': 'Your appointment is reserved. Please send your ',
    'modal.success_p1_part2': ' via Interac E-Transfer to ',
    'modal.success_p1_part3': ' to secure it — without the deposit, your booking may be cancelled.',
    'modal.success_note': 'A CA$15 deposit is required via Interac E-Transfer to dreyvibez1@gmail.com to confirm your appointment.',
    'modal.add_calendar': 'Add to Calendar',
    'modal.progress': 'Progress',
    'modal.step1': 'Step 1 of 3',
    'modal.step2': 'Step 2 of 3',
    'modal.step3': 'Final Step',
    // Careers Section
    'careers.eyebrow': 'Join Our Team',
    'careers.title': 'Careers at DREYCUTZ',
    'careers.desc': 'We\'re always looking for talented, passionate individuals to join the DREYCUTZ family. If you\'re skilled, creative, and dedicated to your craft, we want to hear from you.',
    'careers.apply_now': 'Apply Now',
    'careers.back': 'Back to Positions',
    'careers.form_title': 'Career Application',
    'careers.full_name': 'Full Name',
    'careers.email': 'Email',
    'careers.phone': 'Phone',
    'careers.position': 'Position',
    'careers.address': 'Address',
    'careers.experience': 'Experience & Skills (Optional)',
    'careers.resume': 'Resume (PDF, DOC)',
    'careers.browse': 'Click to browse',
    'careers.supporting_docs': 'Supporting Docs (Optional)',
    'careers.info_note': 'Application opens in your email app. Don\'t forget to attach files.',
    'careers.submit': 'Submit Application',
    'careers.invitation': 'Send your resume and portfolio to:',
    // Gallery Section
    'gallery.work': 'The Work',
    'gallery.motion': 'The Motion',
    'gallery.pictures': 'Pictures',
    'gallery.videos': 'Videos',
    'gallery.photos_desc': 'A curated collection of our finest cuts, atmosphere, and the craft behind every visit.',
    'gallery.videos_desc': 'Cinematic glimpses into the precision and energy of our studio sessions.',
    // Categories
    'category.barbering': 'Barbering',
    'category.locks': 'Locks',
    'category.braiding': 'Braiding & Nails',
  },
  fr: {
    // Navbar
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.about': 'À Propos',
    'nav.gallery': 'Galerie',
    'nav.reviews': 'Avis',
    'nav.contact': 'Contact',
    'nav.booking': 'Réserver',
    // Hero Section
    'hero.eyebrow': 'Studio de Coiffure Premium',
    'hero.welcome': 'Bienvenue chez',
    'hero.subtext': 'Coupes de qualité, lignes précises et soins professionnels à Montréal.',
    'hero.cta_book': 'Prendre RDV',
    'hero.cta_services': 'Nos Services',
    'hero.cta_call': 'Appelez-nous',
    'hero.info_address_label': 'Salon DreyCutz',
    'hero.info_hours_label': 'Heures',
    'hero.info_hours_val': 'Lun – Sam 9h – 19h',
    // About Section
    'about.founder_title': 'PDG & Coiffeur',
    'about.founder_subtitle': 'Fondateur & PDG',
    'about.quote': 'Chaque coupe est un art, chaque détail compte.',
    'about.p1_part1': 'Plus qu’un simple service. Chaque coupe est un ',
    'about.p1_craft': 'art',
    'about.p1_part2': ', chaque détail compte.',
    'about.p2': 'Avec des années d’expérience et une passion pour la précision, Drey apporte expertise, créativité et dévouement à chaque client. Réservez votre séance pour une expérience adaptée à votre structure et style unique.',
    'about.cta': 'Réserver Votre Séance',
    'about.stat_experience': 'Expérience',
    'about.stat_experience_val': '10+ ANS',
    'about.stat_specialty': 'Spécialité',
    'about.stat_specialty_val': 'PRÉCISION',
    'about.stat_location': 'Lieu',
    'about.stat_location_val': 'MONTRÉAL',
    // Values Section
    'values.diff_eyebrow': 'Pourquoi DreyCutz',
    'values.diff_title': 'Le Nouveau Standard',
    'values.diff_desc': 'Nous avons repensé le rituel de soin. Pas d\'attente, pas de compromis, juste un art pur adapté à votre style de vie.',
    'values.card.time_title': 'Gain de Temps',
    'values.card.time_desc': 'Pas d\'attente. Chaque séance est réservée exclusivement pour vous, garantissant la ponctualité.',
    'values.card.skill_title': 'Expertise',
    'values.card.skill_desc': 'Combiner les techniques classiques avec l\'art moderne pour un fini impeccable.',
    'values.card.custom_title': 'Personnalisé',
    'values.card.custom_desc': 'Votre structure osseuse dicte la coupe. Nous concevons pour l\'individu.',
    'values.card.relax_title': 'Relaxant',
    'values.card.relax_desc': 'Un environnement calme et soigné conçu pour vous permettre de recharger vos batteries.',
    'values.core_eyebrow': 'Valeurs Fondamentales',
    'values.core_title': 'Ce en quoi nous croyons',
    'values.val.precision_title': 'Précision',
    'values.val.precision_desc': 'Mesurer deux fois, couper une fois. Nous sommes obsédés par les micro-détails.',
    'values.val.respect_title': 'Respect',
    'values.val.respect_desc': 'Votre temps est sacré. Votre confiance se mérite. Nous traitons chaque client avec dignité.',
    'values.val.integrity_title': 'Intégrité',
    'values.val.integrity_desc': 'Des prix transparents et des conseils honnêtes. Si un style ne vous va pas, on vous le dira.',
    'values.val.excellence_title': 'Excellence',
    'values.val.excellence_desc': 'Le bien est l\'ennemi du mieux. Nous repoussons les limites du métier chaque jour.',
    'values.val.community_title': 'Communauté',
    'values.val.community_desc': 'Un espace où tout le monde a sa place. Plus qu\'un studio, un pilier du quartier.',
    'values.val.passion_title': 'Passion',
    'values.val.passion_desc': 'Ce n\'est pas un travail, c\'est une obsession. Nous vivons pour l\'art de la coupe.',
    // Booking Section
    'booking.title_part1': 'Prêt pour une ',
    'booking.title_fresh': 'Nouvelle',
    'booking.title_part2': ' Coupe ?',
    'booking.tab_services': 'Services',
    'booking.tab_info': 'Infos Studio',
    'booking.menu_title': 'Menu des Services',
    'booking.menu_desc': 'Choisissez une catégorie pour explorer',
    'booking.info_call': 'Appeler',
    'booking.info_email': 'Email',
    'booking.info_location': 'Lieu',
    'booking.popular_times': 'Heures Affluentes',
    'booking.availability_suffix': ' Disponibilité',
    'booking.quiet': 'Calme',
    'booking.moderate': 'Modéré',
    'booking.busy': 'Occupé',
    'booking.schedule_title': 'Horaires du Studio',
    // Reviews Section
    'reviews.eyebrow': 'Nos Clients Satisfaits',
    'reviews.title': 'Les Avis',
    'reviews.rating_label': 'Note 5.0',
    'reviews.verified_client': 'Client Vérifié',
    // Footer Section
    'footer.tagline': 'Salon de coiffure premium à Montréal. Coupes nettes, lignes précises et soins professionnels par Drey.',
    'footer.quick_links': 'Liens Rapides',
    'footer.contact': 'Contact',
    'footer.hours': 'Heures',
    'footer.rights': 'TOUS DROITS RÉSERVÉS.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.link.home': 'Accueil',
    'footer.link.services': 'Nos Services',
    'footer.link.gallery': 'Galerie',
    'footer.link.why_book': 'POURQUOI RÉSERVER CHEZ NOUS',
    'footer.link.about': 'À Propos',
    'footer.link.customers': 'Clients Satisfaits',
    'footer.link.faq': 'FAQ',
    'footer.link.careers': 'Carrières',
    'footer.link.contact': 'Contact',
    // Info Section
    'info.eyebrow': 'Foire Aux Questions',
    'info.title_part1': 'Informations ',
    'info.title_information': 'Essentielles',
    'info.faq_payment_title': 'Modes de Paiement',
    'info.faq_payment_interac': 'Virement Interac',
    'info.faq_payment_cash': 'Espèces (En Studio)',
    'info.faq_payment_note': 'Un dépôt non remboursable est requis au moment de la réservation via Virement Interac.',
    'info.faq_booking_title': 'Politique de Réservation',
    'info.faq_booking_answer': 'Tous les rendez-vous doivent être pris via notre portail en ligne. Votre place n\'est confirmée qu\'une fois le dépôt de 15 $ CA reçu.',
    'info.faq_late_title': 'Politique de Retard',
    'info.faq_late_answer': 'Nous respectons votre temps. Si vous avez plus de 15 minutes de retard, votre rendez-vous peut être annulé pour respecter l\'horaire.',
    'info.notice': 'Avis',
    'info.cancel_title': 'Politique d\'Annulation',
    'info.deposits_label': 'Dépôts',
    'info.deposits_desc': 'Les dépôts sont non remboursables et non transférables si la séance est annulée.',
    'info.reschedule_label': 'Report de RDV',
    'info.reschedule_desc': 'Besoin de déplacer votre séance ? Veuillez nous contacter dès que possible par appel ou SMS.',
    'info.protocol': 'Protocole Studio',
    // Services Section
    'services.title': 'Nos Services',
    'services.explore': 'Découvrir',
    'services.category_label': 'Catégorie',
    'services.crucial_info': 'Informations Cruciales',
    'services.policy_title': 'Politique de Réservation',
    'services.policy_desc': 'Un dépôt non remboursable de 15 $ CA est requis pour garantir votre réservation.',
    'services.book_button': 'Réserver',
    'services.next_category': 'Suivant',
    // Modal Section
    'modal.title_confirmed': 'Réservation Confirmée !',
    'modal.title_booking': 'Prendre Rendez-vous',
    'modal.ready': 'Tout est prêt',
    'modal.close': 'Fermer',
    'modal.select_date': 'Choisir une Date',
    'modal.back_calendar': 'Retour au Calendrier',
    'modal.select_time': 'Choisir une Heure',
    'modal.back_time': 'Retour aux Heures',
    'modal.complete_details': 'Complétez vos détails',
    'modal.first_name': 'Prénom',
    'modal.last_name': 'Nom',
    'modal.email': 'Adresse Email',
    'modal.phone': 'Numéro de Téléphone',
    'modal.confirm_button': 'Confirmer la Réservation',
    'modal.success_p1_part1': 'Votre rendez-vous est réservé. Veuillez envoyer votre ',
    'modal.success_p1_part2': ' par Virement Interac à ',
    'modal.success_p1_part3': ' pour le sécuriser — sans le dépôt, votre réservation peut être annulée.',
    'modal.success_note': 'Un dépôt de 15 $ CA est requis par Virement Interac à dreyvibez1@gmail.com pour confirmer votre rendez-vous.',
    'modal.add_calendar': 'Ajouter au Calendrier',
    'modal.progress': 'Progression',
    'modal.step1': 'Étape 1 sur 3',
    'modal.step2': 'Étape 2 sur 3',
    'modal.step3': 'Dernière Étape',
    // Careers Section
    'careers.eyebrow': 'Rejoignez Notre Équipe',
    'careers.title': 'Carrières chez DREYCUTZ',
    'careers.desc': 'Nous sommes toujours à la recherche de personnes talentueuses et passionnées pour rejoindre la famille DREYCUTZ. Si vous êtes qualifié, créatif et dévoué à votre métier, nous voulons vous entendre.',
    'careers.apply_now': 'Postuler',
    'careers.back': 'Retour aux Postes',
    'careers.form_title': 'Candidature',
    'careers.full_name': 'Nom Complet',
    'careers.email': 'Email',
    'careers.phone': 'Téléphone',
    'careers.position': 'Poste',
    'careers.address': 'Adresse',
    'careers.experience': 'Expérience et Compétences (Optionnel)',
    'careers.resume': 'CV (PDF, DOC)',
    'careers.browse': 'Cliquez pour parcourir',
    'careers.supporting_docs': 'Documents de Soutien (Optionnel)',
    'careers.info_note': 'La candidature s\'ouvre dans votre application de messagerie. N\'oubliez pas de joindre les fichiers.',
    'careers.submit': 'Envoyer la Candidature',
    'careers.invitation': 'Envoyez votre CV et portfolio à :',
    // Gallery Section
    'gallery.work': 'Le Travail',
    'gallery.motion': 'Le Mouvement',
    'gallery.pictures': 'Photos',
    'gallery.videos': 'Vidéos',
    'gallery.photos_desc': 'Une collection soignée de nos plus belles coupes, de l\'ambiance et du métier derrière chaque visite.',
    'gallery.videos_desc': 'Aperçus cinématographiques de la précision et de l\'énergie de nos sessions en studio.',
    // Categories
    'category.barbering': 'Coiffure',
    'category.locks': 'Locks',
    'category.braiding': 'Tresses & Ongles',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  // Load from localStorage if available
  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'fr')) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
